use anchor_lang::prelude::*;
use anchor_lang::solana_program::program_option::COption;
use anchor_spl::associated_token::AssociatedToken;
use anchor_spl::token as spl_token;
use anchor_spl::token::{Mint as SplMint, Token as SplToken, TokenAccount as SplTokenAccount};
use anchor_spl::token_2022::Token2022;
use anchor_spl::token_interface as token_interface;
use anchor_spl::token_interface::{Mint, TokenAccount, TokenInterface};
use mpl_token_metadata::types::TokenStandard;

// NOTE: This must match the deployed program id (and `target/deploy/bunkercash-keypair.json`).
declare_id!("FosyJzxYLREM1u6jEDeBHMuFgMyoHWEoExfXs4W6kvDa");

/// PDA seed for the protocol's single pool state.
pub const POOL_SEED: &[u8] = b"bunkercash_pool";
/// PDA seed for the Bunker Cash mint (Token-2022).
pub const BUNKERCASH_MINT_SEED: &[u8] = b"bunkercash_mint";
/// PDA seed for a pool-controlled signer used to own escrow vaults.
pub const POOL_SIGNER_SEED: &[u8] = b"bunkercash_pool_signer";
/// PDA seed for the per-claim price snapshot captured at sell registration time.
pub const CLAIM_PRICE_SNAPSHOT_SEED: &[u8] = b"bunkercash_claim_price_snapshot";
/// PDA seed for master-ops bookkeeping state.
pub const MASTER_OPS_SEED: &[u8] = b"bunkercash_master_ops";
/// PDA seed for master withdrawal records.
pub const MASTER_WITHDRAWAL_SEED: &[u8] = b"bunkercash_master_withdrawal";

/// Token decimals for the Bunker Cash mint.
pub const BUNKERCASH_DECIMALS: u8 = 9;

// ── Squads governance keys (injected at compile time from programs/bunkercash/.env) ──
// Generated by build.rs into OUT_DIR/squads_keys.rs. Change .env and rebuild.
include!(concat!(env!("OUT_DIR"), "/squads_keys.rs"));

/// Metaplex Token Metadata program id.
pub const TOKEN_METADATA_PROGRAM_ID: Pubkey =
    pubkey!("metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s");

pub const MAX_TOKEN_NAME_LEN: usize = 32;
pub const MAX_TOKEN_SYMBOL_LEN: usize = 10;
pub const MAX_TOKEN_URI_LEN: usize = 200;

/// Max USDC deposit amount (in USDC base units, 6 decimals).
///
/// 1,000,000 USDC * 10^6 = 1_000_000_000_000
pub const MAX_USDC_DEPOSIT_BASE_UNITS: u64 = 1_000_000u64 * 1_000_000u64;

fn owed_usdc_base_units(price_usdc_per_token: u64, token_amount_locked: u64) -> Result<u64> {
    // token_amount_locked has BUNKERCASH_DECIMALS decimals.
    // price_usdc_per_token is USDC base units per 1 whole token.
    let token_scale: u128 = 10u128
        .checked_pow(BUNKERCASH_DECIMALS as u32)
        .ok_or(ErrorCode::MathError)?;
    let owed_u128 = (token_amount_locked as u128)
        .checked_mul(price_usdc_per_token as u128)
        .ok_or(ErrorCode::MathError)?
        .checked_div(token_scale)
        .ok_or(ErrorCode::MathError)?;
    require!(owed_u128 <= u64::MAX as u128, ErrorCode::MathError);
    Ok(owed_u128 as u64)
}

fn next_counter_seed_bytes(counter: u64) -> [u8; 8] {
    counter.saturating_add(1).to_le_bytes()
}

#[program]
pub mod bunkercash {
    use super::*;

    /// Initializes the protocol state and creates the Bunker Cash mint.
    /// All mint/redeem operations use a strict fixed price (`price_usdc_per_token`).
    pub fn initialize(
        ctx: Context<Initialize>,
        admin: Pubkey,
        price_usdc_per_token: u64,
    ) -> Result<()> {
        require!(price_usdc_per_token > 0, ErrorCode::InvalidAmount);

        let pool = &mut ctx.accounts.pool;
        pool.admin = admin;
        pool.price_usdc_per_token = price_usdc_per_token;
        pool.claim_counter = 0;
        pool.bump = ctx.bumps.pool;
        Ok(())
    }

    /// Updates the fixed price (USDC base units per 1 whole token).
    pub fn update_price(ctx: Context<UpdatePrice>, new_price_usdc_per_token: u64) -> Result<()> {
        require!(new_price_usdc_per_token > 0, ErrorCode::InvalidAmount);
        ctx.accounts.pool.price_usdc_per_token = new_price_usdc_per_token;
        Ok(())
    }

    /// Fixed-price primary buy:
    /// - transfer `usdc_amount` from user -> payout USDC vault (legacy SPL token; owned by Pool Signer PDA)
    /// - mint Bunker Cash tokens to user (Token-2022) at fixed price
    ///
    /// The payout vault must already exist. Admin should create it via
    /// `add_liquidity(0)` so the first buyer never pays the ATA rent.
    pub fn buy_primary(ctx: Context<BuyPrimary>, usdc_amount: u64) -> Result<()> {
        require!(usdc_amount > 0, ErrorCode::InvalidAmount);
        require!(
            usdc_amount <= MAX_USDC_DEPOSIT_BASE_UNITS,
            ErrorCode::DepositLimitExceeded
        );

        let price = ctx.accounts.pool.price_usdc_per_token;
        require!(price > 0, ErrorCode::InvalidAmount);
        require!(
            ctx.accounts.bunkercash_mint.decimals == BUNKERCASH_DECIMALS,
            ErrorCode::InvalidMint
        );

        let token_scale: u128 = 10u128
            .checked_pow(BUNKERCASH_DECIMALS as u32)
            .ok_or(ErrorCode::MathError)?;

        let token_amount_u128 = (usdc_amount as u128)
            .checked_mul(token_scale)
            .ok_or(ErrorCode::MathError)?
            .checked_div(price as u128)
            .ok_or(ErrorCode::MathError)?;

        require!(token_amount_u128 > 0, ErrorCode::InvalidAmount);
        require!(token_amount_u128 <= u64::MAX as u128, ErrorCode::MathError);
        let token_amount: u64 = token_amount_u128 as u64;

        // 1) USDC transfer: user -> payout vault (legacy SPL token program)
        spl_token::transfer(
            CpiContext::new(
                ctx.accounts.usdc_token_program.to_account_info(),
                spl_token::Transfer {
                    from: ctx.accounts.user_usdc.to_account_info(),
                    to: ctx.accounts.payout_usdc_vault.to_account_info(),
                    authority: ctx.accounts.user.to_account_info(),
                },
            ),
            usdc_amount,
        )?;

        // 2) Mint Bunker Cash tokens (Token-2022) to user. Mint authority is the pool PDA.
        let seeds: &[&[u8]] = &[POOL_SEED, &[ctx.accounts.pool.bump]];
        token_interface::mint_to(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                token_interface::MintTo {
                    mint: ctx.accounts.bunkercash_mint.to_account_info(),
                    to: ctx.accounts.user_bunkercash.to_account_info(),
                    authority: ctx.accounts.pool.to_account_info(),
                },
                &[seeds],
            ),
            token_amount,
        )?;

        Ok(())
    }

    /// Add USDC liquidity to the protocol payout vault.
    ///
    /// - Transfers `usdc_amount` from admin -> payout USDC vault.
    /// - Vault is an ATA owned by the Pool Signer PDA (deterministic + reusable).
    pub fn add_liquidity(ctx: Context<AddLiquidity>, usdc_amount: u64) -> Result<()> {
        require!(
            usdc_amount <= MAX_USDC_DEPOSIT_BASE_UNITS,
            ErrorCode::DepositLimitExceeded
        );

        // No minimum / guarantee logic: allow `usdc_amount == 0` so the admin can
        // create/verify the vault ATA without necessarily funding it.
        if usdc_amount > 0 {
            spl_token::transfer(
                CpiContext::new(
                    ctx.accounts.usdc_token_program.to_account_info(),
                    spl_token::Transfer {
                        from: ctx.accounts.admin_usdc.to_account_info(),
                        to: ctx.accounts.payout_usdc_vault.to_account_info(),
                        authority: ctx.accounts.admin.to_account_info(),
                    },
                ),
                usdc_amount,
            )?;

            emit!(LiquidityAdded {
                admin: ctx.accounts.admin.key(),
                usdc_mint: ctx.accounts.usdc_mint.key(),
                payout_usdc_vault: ctx.accounts.payout_usdc_vault.key(),
                usdc_amount,
            });
        }

        Ok(())
    }

    /// Process a single claim payout.
    ///
    /// - Pays the exact remaining owed USDC for one claim from the vault to the user.
    /// - Sets `claim.is_closed = true` after payment.
    /// - Only the admin can trigger payouts.
    /// - Requires the vault to hold at least the remaining owed amount.
    pub fn process_claim(ctx: Context<ProcessClaim>) -> Result<()> {
        let claim = &mut ctx.accounts.claim;

        let owed = owed_usdc_base_units(
            ctx.accounts.claim_price_snapshot.price_usdc_per_token,
            claim.token_amount_locked,
        )?;
        require!(owed > 0, ErrorCode::ClaimPayoutTooSmall);

        let remaining = owed.saturating_sub(claim.usdc_paid);

        if remaining > 0 {
            require!(
                ctx.accounts.payout_usdc_vault.amount >= remaining,
                ErrorCode::InsufficientVaultFunds
            );

            let pool_key = ctx.accounts.pool.key();
            let signer_seeds: &[&[u8]] = &[
                POOL_SIGNER_SEED,
                pool_key.as_ref(),
                &[ctx.bumps.pool_signer],
            ];

            spl_token::transfer(
                CpiContext::new_with_signer(
                    ctx.accounts.usdc_token_program.to_account_info(),
                    spl_token::Transfer {
                        from: ctx.accounts.payout_usdc_vault.to_account_info(),
                        to: ctx.accounts.user_usdc.to_account_info(),
                        authority: ctx.accounts.pool_signer.to_account_info(),
                    },
                    &[signer_seeds],
                ),
                remaining,
            )?;

            claim.usdc_paid = owed;
        }

        claim.is_closed = true;

        Ok(())
    }   

    /// Irreversible sell registration:
    /// - transfer `token_amount` of Bunker Cash from the user into a program-owned escrow vault (Token-2022)
    /// - create a ClaimState record
    /// - increment `claim_counter`
    ///
    /// IMPORTANT: No burn is allowed in this flow.
    pub fn register_sell(ctx: Context<RegisterSell>, token_amount: u64) -> Result<()> {
        require!(token_amount > 0, ErrorCode::InvalidAmount);

        require!(
            ctx.accounts.bunkercash_mint.decimals == BUNKERCASH_DECIMALS,
            ErrorCode::InvalidMint
        );

        let owed = owed_usdc_base_units(
            ctx.accounts.pool.price_usdc_per_token,
            token_amount,
        )?;
        require!(owed > 0, ErrorCode::ClaimPayoutTooSmall);

        // 1) Lock user's Bunker Cash tokens into the escrow vault (Token-2022).
        token_interface::transfer_checked(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                token_interface::TransferChecked {
                    from: ctx.accounts.user_bunkercash.to_account_info(),
                    to: ctx.accounts.escrow_bunkercash_vault.to_account_info(),
                    authority: ctx.accounts.user.to_account_info(),
                    mint: ctx.accounts.bunkercash_mint.to_account_info(),
                },
            ),
            token_amount,
            ctx.accounts.bunkercash_mint.decimals,
        )?;

        // 2) Increment counter and write claim record.
        let pool = &mut ctx.accounts.pool;
        let next_id = pool
            .claim_counter
            .checked_add(1)
            .ok_or(ErrorCode::MathError)?;
        pool.claim_counter = next_id;

        let claim = &mut ctx.accounts.claim;
        claim.id = next_id;
        claim.user = ctx.accounts.user.key();
        claim.token_amount_locked = token_amount;
        claim.usdc_paid = 0;
        claim.is_closed = false;
        claim.created_at = Clock::get()?.unix_timestamp;
        claim.bump = ctx.bumps.claim;

        let claim_price_snapshot = &mut ctx.accounts.claim_price_snapshot;
        claim_price_snapshot.claim = claim.key();
        claim_price_snapshot.price_usdc_per_token = ctx.accounts.pool.price_usdc_per_token;
        claim_price_snapshot.bump = ctx.bumps.claim_price_snapshot;

        Ok(())
    }

    /// Admin withdrawal from the current payout vault.
    ///
    /// - Transfers `amount` USDC from the payout vault to the admin USDC account.
    /// - Creates a `MasterWithdrawalState` record for later repayment/cancellation bookkeeping.
    /// - Uses a separate master-ops PDA so the deployed pool account does not need resizing.
    pub fn master_withdraw(
        ctx: Context<MasterWithdraw>,
        amount: u64,
        metadata_hash: [u8; 32],
    ) -> Result<()> {
        require!(amount > 0, ErrorCode::InvalidAmount);
        require!(
            ctx.accounts.payout_usdc_vault.amount >= amount,
            ErrorCode::InsufficientVaultFunds
        );

        let pool_key = ctx.accounts.pool.key();
        let signer_seeds: &[&[u8]] = &[
            POOL_SIGNER_SEED,
            pool_key.as_ref(),
            &[ctx.bumps.pool_signer],
        ];

        spl_token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.usdc_token_program.to_account_info(),
                spl_token::Transfer {
                    from: ctx.accounts.payout_usdc_vault.to_account_info(),
                    to: ctx.accounts.admin_usdc.to_account_info(),
                    authority: ctx.accounts.pool_signer.to_account_info(),
                },
                &[signer_seeds],
            ),
            amount,
        )?;

        let master_ops = &mut ctx.accounts.master_ops;
        master_ops.withdrawal_counter = master_ops
            .withdrawal_counter
            .checked_add(1)
            .ok_or(ErrorCode::MathError)?;
        master_ops.bump = ctx.bumps.master_ops;

        let withdrawal = &mut ctx.accounts.withdrawal;
        withdrawal.pool = pool_key;
        withdrawal.id = master_ops.withdrawal_counter;
        withdrawal.amount = amount;
        withdrawal.remaining = amount;
        withdrawal.repaid_amount = 0;
        withdrawal.cancelled_amount = 0;
        withdrawal.metadata_hash = metadata_hash;
        withdrawal.created_at = Clock::get()?.unix_timestamp;
        withdrawal.bump = ctx.bumps.withdrawal;

        emit!(MasterWithdrawalCreated {
            id: withdrawal.id,
            admin: ctx.accounts.admin.key(),
            payout_usdc_vault: ctx.accounts.payout_usdc_vault.key(),
            admin_usdc: ctx.accounts.admin_usdc.key(),
            amount,
            metadata_hash,
        });

        Ok(())
    }

    /// Repays part or all of a previously recorded admin withdrawal back into the payout vault.
    pub fn master_repay(ctx: Context<MasterRepay>, amount: u64) -> Result<()> {
        require!(amount > 0, ErrorCode::InvalidAmount);

        let withdrawal = &mut ctx.accounts.withdrawal;
        require!(withdrawal.remaining >= amount, ErrorCode::WithdrawalAmountExceeded);

        spl_token::transfer(
            CpiContext::new(
                ctx.accounts.usdc_token_program.to_account_info(),
                spl_token::Transfer {
                    from: ctx.accounts.admin_usdc.to_account_info(),
                    to: ctx.accounts.payout_usdc_vault.to_account_info(),
                    authority: ctx.accounts.admin.to_account_info(),
                },
            ),
            amount,
        )?;

        withdrawal.remaining = withdrawal
            .remaining
            .checked_sub(amount)
            .ok_or(ErrorCode::MathError)?;
        withdrawal.repaid_amount = withdrawal
            .repaid_amount
            .checked_add(amount)
            .ok_or(ErrorCode::MathError)?;

        emit!(MasterWithdrawalRepaid {
            id: withdrawal.id,
            admin: ctx.accounts.admin.key(),
            amount,
            remaining: withdrawal.remaining,
        });

        Ok(())
    }

    /// Cancels part or all of a previously recorded admin withdrawal by returning funds to the payout vault.
    pub fn master_cancel_withdrawal(
        ctx: Context<MasterCancelWithdrawal>,
        amount: u64,
    ) -> Result<()> {
        require!(amount > 0, ErrorCode::InvalidAmount);

        let withdrawal = &mut ctx.accounts.withdrawal;
        require!(withdrawal.remaining >= amount, ErrorCode::WithdrawalAmountExceeded);

        spl_token::transfer(
            CpiContext::new(
                ctx.accounts.usdc_token_program.to_account_info(),
                spl_token::Transfer {
                    from: ctx.accounts.admin_usdc.to_account_info(),
                    to: ctx.accounts.payout_usdc_vault.to_account_info(),
                    authority: ctx.accounts.admin.to_account_info(),
                },
            ),
            amount,
        )?;

        withdrawal.remaining = withdrawal
            .remaining
            .checked_sub(amount)
            .ok_or(ErrorCode::MathError)?;
        withdrawal.cancelled_amount = withdrawal
            .cancelled_amount
            .checked_add(amount)
            .ok_or(ErrorCode::MathError)?;

        emit!(MasterWithdrawalCancelled {
            id: withdrawal.id,
            admin: ctx.accounts.admin.key(),
            amount,
            remaining: withdrawal.remaining,
        });

        Ok(())
    }

    /// Creates Metaplex token metadata for the Bunker Cash mint (Token-2022).
    ///
    /// This is required for wallets (e.g. Phantom) to display the token as `bRENT`
    /// instead of "Unknown Token".
    ///
    /// Notes:
    /// - Mint authority is the pool PDA, so we must CPI from this program to sign as the PDA.
    /// - Restricted to the pool admin.
    pub fn init_mint_metadata(
        ctx: Context<InitMintMetadata>,
        name: String,
        symbol: String,
        uri: String,
    ) -> Result<()> {
        require!(
            name.as_bytes().len() <= MAX_TOKEN_NAME_LEN,
            ErrorCode::InvalidMetadata
        );
        require!(
            symbol.as_bytes().len() <= MAX_TOKEN_SYMBOL_LEN,
            ErrorCode::InvalidMetadata
        );
        require!(
            uri.as_bytes().len() <= MAX_TOKEN_URI_LEN,
            ErrorCode::InvalidMetadata
        );

        require_keys_eq!(
            ctx.accounts.token_metadata_program.key(),
            TOKEN_METADATA_PROGRAM_ID,
            ErrorCode::InvalidMetadataProgram
        );

        // Validate the metadata PDA address for this mint.
        let (expected_metadata, _) = mpl_token_metadata::accounts::Metadata::find_pda(
            &ctx.accounts.bunkercash_mint.key(),
        );
        require_keys_eq!(
            ctx.accounts.metadata.key(),
            expected_metadata,
            ErrorCode::InvalidMetadataPda
        );

        let seeds: &[&[u8]] = &[POOL_SEED, &[ctx.accounts.pool.bump]];

        // Create the metadata account using CreateV1 (supports Token-2022 when passing spl_token_program).
        // Update authority is the admin signer so metadata can be updated later.
        let token_metadata_program = ctx.accounts.token_metadata_program.to_account_info();
        let metadata = ctx.accounts.metadata.to_account_info();
        let mint = ctx.accounts.bunkercash_mint.to_account_info();
        let pool = ctx.accounts.pool.to_account_info();
        let admin = ctx.accounts.admin.to_account_info();
        let system_program = ctx.accounts.system_program.to_account_info();
        let sysvar_instructions = ctx.accounts.sysvar_instructions.to_account_info();
        let spl_token_program = ctx.accounts.token_program.to_account_info();

        mpl_token_metadata::instructions::CreateV1CpiBuilder::new(&token_metadata_program)
            .metadata(&metadata)
            .master_edition(None)
            .mint(&mint, false) // existing mint account, not a signer
            .authority(&pool)
            .payer(&admin)
            .update_authority(&admin, true)
            .system_program(&system_program)
            .sysvar_instructions(&sysvar_instructions)
            .spl_token_program(Some(&spl_token_program))
            .name(name)
            .symbol(symbol)
            .uri(uri)
            .seller_fee_basis_points(0)
            .primary_sale_happened(false)
            .is_mutable(true)
            .token_standard(TokenStandard::Fungible)
            .decimals(BUNKERCASH_DECIMALS)
            .invoke_signed(&[seeds])?;

        Ok(())
    }

    /// Updates Metaplex token metadata for the Bunker Cash mint.
    pub fn update_mint_metadata(
        ctx: Context<UpdateMintMetadata>,
        name: String,
        symbol: String,
        uri: String,
    ) -> Result<()> {
        require!(name.as_bytes().len() <= MAX_TOKEN_NAME_LEN, ErrorCode::InvalidMetadata);
        require!(symbol.as_bytes().len() <= MAX_TOKEN_SYMBOL_LEN, ErrorCode::InvalidMetadata);
        require!(uri.as_bytes().len() <= MAX_TOKEN_URI_LEN, ErrorCode::InvalidMetadata);

        let data = mpl_token_metadata::types::Data {
            name,
            symbol,
            uri,
            seller_fee_basis_points: 0,
            creators: None,
        };

        mpl_token_metadata::instructions::UpdateV1CpiBuilder::new(
            &ctx.accounts.token_metadata_program.to_account_info(),
        )
            .metadata(&ctx.accounts.metadata.to_account_info())
            .mint(&ctx.accounts.bunkercash_mint.to_account_info())
            .authority(&ctx.accounts.admin.to_account_info())
            .payer(&ctx.accounts.admin.to_account_info())
            .system_program(&ctx.accounts.system_program.to_account_info())
            .sysvar_instructions(&ctx.accounts.sysvar_instructions.to_account_info())
            .data(data)
            .is_mutable(true)
            .invoke()?;

        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = payer,
        space = 8 + PoolState::INIT_SPACE,
        seeds = [POOL_SEED],
        bump
    )]
    pub pool: Account<'info, PoolState>,

    #[account(
        init,
        payer = payer,
        seeds = [BUNKERCASH_MINT_SEED],
        bump,
        mint::decimals = BUNKERCASH_DECIMALS,
        mint::authority = pool,
        mint::token_program = token_program
    )]
    pub bunkercash_mint: InterfaceAccount<'info, Mint>,

    #[account(mut)]
    pub payer: Signer<'info>,

    /// Token program for Bunker Cash mint (Token-2022).
    pub token_program: Interface<'info, TokenInterface>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdatePrice<'info> {
    #[account(
        mut,
        seeds = [POOL_SEED],
        bump = pool.bump,
        // Direct (pre-governance): admin signer must equal pool.admin.
        // Governed (Squads): pool.admin is the multisig, but the vault signs when executing.
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,
    pub admin: Signer<'info>,
}

#[derive(Accounts)]
pub struct BuyPrimary<'info> {
    #[account(
        mut,
        seeds = [POOL_SEED],
        bump = pool.bump
    )]
    pub pool: Account<'info, PoolState>,

    /// PDA that owns all program vault ATAs (escrow + payout).
    /// CHECK: PDA is derived and used only as a vault owner/authority.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    #[account(
        mut,
        seeds = [BUNKERCASH_MINT_SEED],
        bump,
        constraint = bunkercash_mint.mint_authority == COption::Some(pool.key()) @ ErrorCode::InvalidMintAuthority
    )]
    pub bunkercash_mint: InterfaceAccount<'info, Mint>,

    #[account(mut)]
    pub user: Signer<'info>,

    pub usdc_mint: Account<'info, SplMint>,

    #[account(
        mut,
        constraint = user_usdc.owner == user.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = user_usdc.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub user_usdc: Account<'info, SplTokenAccount>,

    #[account(
        mut,
        constraint = payout_usdc_vault.owner == pool_signer.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = payout_usdc_vault.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub payout_usdc_vault: Account<'info, SplTokenAccount>,

    #[account(
        mut,
        constraint = user_bunkercash.owner == user.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = user_bunkercash.mint == bunkercash_mint.key() @ ErrorCode::InvalidMint
    )]
    pub user_bunkercash: InterfaceAccount<'info, TokenAccount>,

    pub usdc_token_program: Program<'info, SplToken>,
    /// Token program for Bunker Cash mint (Token-2022).
    pub token_program: Interface<'info, TokenInterface>,
}

#[derive(Accounts)]
pub struct AddLiquidity<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        // Direct (pre-governance): admin signer must equal pool.admin.
        // Governed (Squads): pool.admin is the multisig, but the vault signs when executing.
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    /// PDA that owns all program vault ATAs (escrow + payout).
    /// CHECK: PDA is derived and used only as a vault owner/authority.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    pub usdc_mint: Account<'info, SplMint>,

    #[account(mut)]
    pub admin: Signer<'info>,

    #[account(
        mut,
        constraint = admin_usdc.owner == admin.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = admin_usdc.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub admin_usdc: Account<'info, SplTokenAccount>,

    #[account(
        init_if_needed,
        payer = admin,
        associated_token::mint = usdc_mint,
        associated_token::authority = pool_signer,
        associated_token::token_program = usdc_token_program,
        constraint = payout_usdc_vault.owner == pool_signer.key() @ ErrorCode::InvalidTokenAccountOwner
    )]
    pub payout_usdc_vault: Account<'info, SplTokenAccount>,

    pub usdc_token_program: Program<'info, SplToken>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ProcessClaim<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        // Direct (pre-governance): admin signer must equal pool.admin.
        // Governed (Squads): pool.admin is the multisig, but the vault signs when executing.
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    /// PDA that owns all program vault ATAs (escrow + payout).
    /// CHECK: PDA is derived and used only as a vault owner/authority.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    #[account(mut)]
    pub admin: Signer<'info>,

    #[account(
        mut,
        close = claim_rent_recipient,
        constraint = !claim.is_closed @ ErrorCode::ClaimClosed
    )]
    pub claim: Account<'info, ClaimState>,

    #[account(
        mut,
        close = claim_rent_recipient,
        seeds = [CLAIM_PRICE_SNAPSHOT_SEED, claim.key().as_ref()],
        bump = claim_price_snapshot.bump,
        constraint = claim_price_snapshot.claim == claim.key() @ ErrorCode::InvalidClaimPriceSnapshot
    )]
    pub claim_price_snapshot: Account<'info, ClaimPriceSnapshotState>,

    /// CHECK: Receives rent refunds for closed claim accounts; must be the original claimer.
    #[account(mut, constraint = claim_rent_recipient.key() == claim.user @ ErrorCode::InvalidClaimUser)]
    pub claim_rent_recipient: UncheckedAccount<'info>,

    pub usdc_mint: Account<'info, SplMint>,

    #[account(
        mut,
        constraint = payout_usdc_vault.owner == pool_signer.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = payout_usdc_vault.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub payout_usdc_vault: Account<'info, SplTokenAccount>,

    /// The claim user's USDC token account (recipient of the payout).
    #[account(
        mut,
        constraint = user_usdc.owner == claim.user @ ErrorCode::InvalidClaimUserTokenAccount,
        constraint = user_usdc.mint == payout_usdc_vault.mint @ ErrorCode::InvalidMint
    )]
    pub user_usdc: Account<'info, SplTokenAccount>,

    pub usdc_token_program: Program<'info, SplToken>,
}

#[derive(Accounts)]
pub struct RegisterSell<'info> {
    #[account(
        mut,
        seeds = [POOL_SEED],
        bump = pool.bump
    )]
    pub pool: Account<'info, PoolState>,

    /// PDA that owns all program vault ATAs (escrow + payout).
    /// CHECK: PDA is derived and used only as a vault owner.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    #[account(
        mut,
        seeds = [BUNKERCASH_MINT_SEED],
        bump,
        constraint = bunkercash_mint.mint_authority == COption::Some(pool.key()) @ ErrorCode::InvalidMintAuthority
    )]
    pub bunkercash_mint: InterfaceAccount<'info, Mint>,

    #[account(
        init,
        payer = user,
        space = 8 + ClaimState::INIT_SPACE,
        seeds = [
            b"claim",
            pool.key().as_ref(),
            &next_counter_seed_bytes(pool.claim_counter)
        ],
        bump
    )]
    pub claim: Account<'info, ClaimState>,

    #[account(
        init,
        payer = user,
        space = 8 + ClaimPriceSnapshotState::INIT_SPACE,
        seeds = [CLAIM_PRICE_SNAPSHOT_SEED, claim.key().as_ref()],
        bump
    )]
    pub claim_price_snapshot: Account<'info, ClaimPriceSnapshotState>,

    #[account(mut)]
    pub user: Signer<'info>,

    #[account(
        mut,
        constraint = user_bunkercash.owner == user.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = user_bunkercash.mint == bunkercash_mint.key() @ ErrorCode::InvalidMint
    )]
    pub user_bunkercash: InterfaceAccount<'info, TokenAccount>,

    #[account(
        init_if_needed,
        payer = user,
        associated_token::mint = bunkercash_mint,
        associated_token::authority = pool_signer,
        associated_token::token_program = token_program
    )]
    pub escrow_bunkercash_vault: InterfaceAccount<'info, TokenAccount>,

    /// Token program for the Bunker Cash mint (Token-2022).
    pub token_program: Interface<'info, TokenInterface>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct MasterWithdraw<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    #[account(
        init_if_needed,
        payer = admin,
        space = 8 + MasterOpsState::INIT_SPACE,
        seeds = [MASTER_OPS_SEED, pool.key().as_ref()],
        bump
    )]
    pub master_ops: Account<'info, MasterOpsState>,

    /// CHECK: PDA is derived and used only as a vault owner/authority.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    #[account(
        init,
        payer = admin,
        space = 8 + MasterWithdrawalState::INIT_SPACE,
        seeds = [
            MASTER_WITHDRAWAL_SEED,
            pool.key().as_ref(),
            &next_counter_seed_bytes(master_ops.withdrawal_counter)
        ],
        bump
    )]
    pub withdrawal: Account<'info, MasterWithdrawalState>,

    #[account(mut)]
    pub admin: Signer<'info>,

    pub usdc_mint: Account<'info, SplMint>,

    #[account(
        mut,
        constraint = payout_usdc_vault.owner == pool_signer.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = payout_usdc_vault.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub payout_usdc_vault: Account<'info, SplTokenAccount>,

    #[account(
        mut,
        constraint = admin_usdc.owner == admin.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = admin_usdc.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub admin_usdc: Account<'info, SplTokenAccount>,

    pub usdc_token_program: Program<'info, SplToken>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct MasterRepay<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    #[account(
        seeds = [MASTER_OPS_SEED, pool.key().as_ref()],
        bump = master_ops.bump
    )]
    pub master_ops: Account<'info, MasterOpsState>,

    /// CHECK: PDA is derived and used only as a vault owner/authority.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    #[account(
        mut,
        constraint = withdrawal.id > 0 @ ErrorCode::InvalidWithdrawalAccount,
        constraint = withdrawal.pool == pool.key() @ ErrorCode::InvalidWithdrawalAccount
    )]
    pub withdrawal: Account<'info, MasterWithdrawalState>,

    #[account(mut)]
    pub admin: Signer<'info>,

    pub usdc_mint: Account<'info, SplMint>,

    #[account(
        mut,
        constraint = payout_usdc_vault.owner == pool_signer.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = payout_usdc_vault.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub payout_usdc_vault: Account<'info, SplTokenAccount>,

    #[account(
        mut,
        constraint = admin_usdc.owner == admin.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = admin_usdc.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub admin_usdc: Account<'info, SplTokenAccount>,

    pub usdc_token_program: Program<'info, SplToken>,
}

#[derive(Accounts)]
pub struct MasterCancelWithdrawal<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    #[account(
        seeds = [MASTER_OPS_SEED, pool.key().as_ref()],
        bump = master_ops.bump
    )]
    pub master_ops: Account<'info, MasterOpsState>,

    /// CHECK: PDA is derived and used only as a vault owner/authority.
    #[account(
        seeds = [POOL_SIGNER_SEED, pool.key().as_ref()],
        bump
    )]
    pub pool_signer: UncheckedAccount<'info>,

    #[account(
        mut,
        constraint = withdrawal.id > 0 @ ErrorCode::InvalidWithdrawalAccount,
        constraint = withdrawal.pool == pool.key() @ ErrorCode::InvalidWithdrawalAccount
    )]
    pub withdrawal: Account<'info, MasterWithdrawalState>,

    #[account(mut)]
    pub admin: Signer<'info>,

    pub usdc_mint: Account<'info, SplMint>,

    #[account(
        mut,
        constraint = payout_usdc_vault.owner == pool_signer.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = payout_usdc_vault.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub payout_usdc_vault: Account<'info, SplTokenAccount>,

    #[account(
        mut,
        constraint = admin_usdc.owner == admin.key() @ ErrorCode::InvalidTokenAccountOwner,
        constraint = admin_usdc.mint == usdc_mint.key() @ ErrorCode::InvalidMint
    )]
    pub admin_usdc: Account<'info, SplTokenAccount>,

    pub usdc_token_program: Program<'info, SplToken>,
}

#[derive(Accounts)]
pub struct InitMintMetadata<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        // Direct (pre-governance): admin signer must equal pool.admin.
        // Governed (Squads): pool.admin is the multisig, but the vault signs when executing.
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    #[account(
        mut,
        seeds = [BUNKERCASH_MINT_SEED],
        bump,
        constraint = bunkercash_mint.mint_authority == COption::Some(pool.key()) @ ErrorCode::InvalidMintAuthority
    )]
    pub bunkercash_mint: InterfaceAccount<'info, Mint>,

    #[account(mut)]
    pub admin: Signer<'info>,

    /// Metaplex metadata PDA for the mint.
    /// CHECK: Address is validated in the instruction.
    #[account(mut)]
    pub metadata: UncheckedAccount<'info>,

    /// Metaplex Token Metadata program.
    /// CHECK: Address is validated in the instruction.
    pub token_metadata_program: UncheckedAccount<'info>,

    /// Token-2022 program (passed to Metaplex as `spl_token_program`).
    pub token_program: Program<'info, Token2022>,

    /// Instructions sysvar required by Metaplex CreateV1.
    /// CHECK: sysvar account.
    pub sysvar_instructions: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateMintMetadata<'info> {
    #[account(
        seeds = [POOL_SEED],
        bump = pool.bump,
        constraint = (admin.key() == pool.admin)
            || (pool.admin == SQUADS_MULTISIG_PUBKEY && admin.key() == SQUADS_VAULT_PUBKEY)
            @ ErrorCode::Unauthorized
    )]
    pub pool: Account<'info, PoolState>,

    #[account(
        seeds = [BUNKERCASH_MINT_SEED],
        bump,
    )]
    pub bunkercash_mint: InterfaceAccount<'info, Mint>,

    #[account(mut)]
    pub admin: Signer<'info>,

    /// CHECK: Metaplex metadata PDA
    #[account(mut)]
    pub metadata: UncheckedAccount<'info>,

    /// CHECK: Validated by address
    #[account(address = TOKEN_METADATA_PROGRAM_ID @ ErrorCode::InvalidMetadataProgram)]
    pub token_metadata_program: UncheckedAccount<'info>,

    /// CHECK: sysvar
    pub sysvar_instructions: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,
}

#[account]
#[derive(InitSpace)]
pub struct PoolState {
    pub admin: Pubkey,
    /// USDC base units per 1 whole token.
    pub price_usdc_per_token: u64,
    pub claim_counter: u64,
    pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct ClaimState {
    pub id: u64,
    pub user: Pubkey,
    pub token_amount_locked: u64,
    pub usdc_paid: u64,
    pub is_closed: bool,
    pub created_at: i64,
    pub bump: u8,
}

/// Price snapshot stored separately from `ClaimState` so existing deployed claim
/// accounts remain deserializable without resizing migrations.
#[account]
#[derive(InitSpace)]
pub struct ClaimPriceSnapshotState {
    pub claim: Pubkey,
    pub price_usdc_per_token: u64,
    pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct MasterOpsState {
    pub withdrawal_counter: u64,
    pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct MasterWithdrawalState {
    pub pool: Pubkey,
    pub id: u64,
    pub amount: u64,
    pub remaining: u64,
    pub repaid_amount: u64,
    pub cancelled_amount: u64,
    pub metadata_hash: [u8; 32],
    pub created_at: i64,
    pub bump: u8,
}

#[error_code]
pub enum ErrorCode {
    #[msg("Invalid amount")]
    InvalidAmount,
    #[msg("Deposit exceeds maximum allowed amount")]
    DepositLimitExceeded,
    #[msg("Unauthorized")]
    Unauthorized,
    #[msg("Math error")]
    MathError,
    #[msg("Insufficient USDC in vault")]
    InsufficientVaultFunds,
    #[msg("Invalid token account owner")]
    InvalidTokenAccountOwner,
    #[msg("Invalid mint")]
    InvalidMint,
    #[msg("Invalid mint authority")]
    InvalidMintAuthority,
    #[msg("Invalid token metadata")]
    InvalidMetadata,
    #[msg("Invalid token metadata program")]
    InvalidMetadataProgram,
    #[msg("Invalid token metadata PDA")]
    InvalidMetadataPda,
    #[msg("Claim is already closed")]
    ClaimClosed,
    #[msg("Claim user does not match provided user")]
    InvalidClaimUser,
    #[msg("Invalid remaining accounts for pro-rata payouts")]
    InvalidRemainingAccounts,
    #[msg("Provided user USDC account does not belong to claim user")]
    InvalidClaimUserTokenAccount,
    #[msg("Invalid claim account")]
    InvalidClaimAccount,
    #[msg("User USDC token account must be writable")]
    UserUsdcNotWritable,
    #[msg("Withdrawal amount exceeds the remaining balance")]
    WithdrawalAmountExceeded,
    #[msg("Invalid withdrawal account")]
    InvalidWithdrawalAccount,
    #[msg("Claim price snapshot is invalid")]
    InvalidClaimPriceSnapshot,
    #[msg("Claim payout rounds down to zero")]
    ClaimPayoutTooSmall,
}

/// Emitted when the admin deposits USDC into the payout vault.
#[event]
pub struct LiquidityAdded {
    pub admin: Pubkey,
    pub usdc_mint: Pubkey,
    pub payout_usdc_vault: Pubkey,
    pub usdc_amount: u64,
}

#[event]
pub struct MasterWithdrawalCreated {
    pub id: u64,
    pub admin: Pubkey,
    pub payout_usdc_vault: Pubkey,
    pub admin_usdc: Pubkey,
    pub amount: u64,
    pub metadata_hash: [u8; 32],
}

#[event]
pub struct MasterWithdrawalRepaid {
    pub id: u64,
    pub admin: Pubkey,
    pub amount: u64,
    pub remaining: u64,
}

#[event]
pub struct MasterWithdrawalCancelled {
    pub id: u64,
    pub admin: Pubkey,
    pub amount: u64,
    pub remaining: u64,
}
